### ISSUE TITLE
 the derivation of Fxt = Tr * 3 / (2 * H)

### ISSUE THREAD

**Issue by xsy1986** [antjedittmer/2021-code-A-Velocity-quasiLPV-MPC-Algorithm-for-Wind-Turbine-Control#1]
Dear Professor Dittmer,

I hope this message finds you well.  I recently had the opportunity to read your paper titled " A Velocity quasiLPV-MPC Algorithm for Wind Turbine Control." Additionally, I downloaded the corresponding Simulink model from GitHub. 

I have a question that I find quite perplexing, and I would greatly appreciate your assistance. In your paper, you refer to Fxt as the tower side-to-side force. However, in the Simulink model, I observed that the calculation for this force is represented as follows: Fxt = Tr * 3 / (2 * H), where Tr denotes the aerodynamic torque and H represents the tower height. 

I am curious about the derivation of this formula and would be grateful if you could provide an explanation of the process involved. Thank you very much for your time and assistance.

Sincerely,

**Comment by antjedittmer** [comment]
Hello,

thank you for reaching out and for your interest in our research.

We used the term 2/3 Ht, with Ht as the tower height, as a lever to relate the unknown side-to-side force F_xt, acting at hub height on the tower, to the rotor torque T_r, which we use as an input. We selected this ratio between the rotor torque and the force because it aligns with the effective point of action for a triangularly distributed load (see, e.g., here: https://engineeringstatics.org/distributed-loads.html).

The MATLAB implementation can be found here: https://github.com/TUHH-ICS/2021-code-A-Velocity-quasiLPV-MPC-Algorithm-for-Wind-Turbine-Control/blob/master/LinMdl/compareLinearModels.m, where the factor is defined in line 91:
ksw = 3 / (2 * wecs.H);

I visually verified that the low-frequency similarity (0.01 to 0.7 Hz) appears reasonable when compared to the FAST reference. Please see the attached Bode plot at 4 m/s.

I hope this answers your question.

Kind regards,
Antje

P.S. There are two small caveats:
-	You will see that the fit for the side-to-side force is reasonable but not as accurate as it is for the fore-aft force or the rotor speed. Specifically, the influence of the wind on side-to-side movement is not modeled as well in our simple model as it is for the other axes.
-	Unfortunately, there is an error in the paper and the code that I have since corrected: The side-to-side force is related to the torque acting at hub height, which should be the difference between rotor torque and generator torque, not the rotor torque alone. Therefore, it should be: F_xt = ksw * (Tr - Ng * Tg), where Tr is the rotor torque, Tg is the generator torque, and Ng is the gear ratio.

Please note that both the model mismatch in the side-to-side movement and this mistake have only a negligible influence on the results shown in the paper due to the very small amplitudes of the side-to-side movement, which are smaller than the fore-aft movements by a factor of roughly 50. See the attached time series plot of a stepped wind sweep for reference.

![Figure_Bode V = 4, pitch = 0 00, and TSR = 7 5688](https://github.com/user-attachments/assets/4069807c-175e-44da-a000-46ec0c2cc7e0)

![cmpTimeDomain_All](https://github.com/user-attachments/assets/456cf351-09e7-45ea-8238-9885d5d99ff9)
